# Generated by Django 3.1.2 on 2020-10-10 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('ISBN', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('BookTitle', models.CharField(max_length=144)),
                ('Description', models.TextField()),
                ('Images', models.ImageField(upload_to='media')),
                ('Quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('BookId', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('IssueDate', models.DateField(blank=True)),
                ('DueDate', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('FullName', models.CharField(max_length=13)),
                ('RollNumber', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('ProfileImage', models.ImageField(upload_to='media/dp')),
                ('BorrowedBook', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='lms.bookinstance')),
            ],
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='Borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lms.member'),
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='ISBN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.book'),
        ),
    ]
