# Generated by Django 3.1.2 on 2020-10-10 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='Borrower',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='lms.member'),
        ),
    ]
