# Generated by Django 3.1.2 on 2020-10-10 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_auto_20201010_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='Borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='lms.member'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='DueDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='IssueDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
