# Generated by Django 3.1.2 on 2020-10-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_auto_20201010_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='id',
            field=models.AutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='id',
            field=models.AutoField(auto_created=True, default=3, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='BookId',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='RollNumber',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
