# Generated by Django 3.1.2 on 2020-10-11 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_auto_20201010_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isApproved', models.IntegerField(choices=[(1, 'Pending'), (1, 'Approved'), (2, 'Rejected')], default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='Borrower',
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='DueDate',
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='IssueDate',
        ),
        migrations.RemoveField(
            model_name='member',
            name='BorrowedBook',
        ),
        migrations.AlterField(
            model_name='book',
            name='Images',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IssueDate', models.DateField()),
                ('DueDate', models.DateField()),
                ('Request', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lms.issuerequest')),
            ],
        ),
        migrations.AddField(
            model_name='issuerequest',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lms.bookinstance'),
        ),
        migrations.AddField(
            model_name='issuerequest',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lms.member'),
        ),
    ]
