# Generated by Django 3.1.2 on 2020-10-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_auto_20201011_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
