# Generated by Django 3.1.2 on 2020-10-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0009_bookinstance_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='Images',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
