# Generated by Django 3.1.2 on 2020-10-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0010_bookinstance_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='Condition',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Good'), (2, 'Superficial Damage'), (3, 'Missing Pages')], default=0),
        ),
    ]
