# Generated by Django 3.1.2 on 2020-10-13 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0011_bookinstance_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='last_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lms.transactions'),
        ),
    ]
